---
# Source: https://github.com/geerlingguy/ansible-role-mysql/blob/master/.travis.yml

services: docker

env:
  - distro: centos7
    playbook: test.yml
  - distro: debian8
    playbook: test.yml
  - distro: ubuntu1604
    playbook: test.yml

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/Phill93/9893096e9a26cedc3b6db5d4f7df5e7c/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  - sudo docker exec ${container_id} lsof -i4TCP:ldap >> /dev/null && (echo 'LDAP Socket open' && exit 0) || (echo 'LDAP Socket closed' && exit 1)
  - sudo docker exec ${container_id} lsof -i4TCP:ldaps >> /dev/null && (echo 'Secure LDAP Socket open' && exit 0) || (echo 'Secure LDAP Socket closed' && exit 1)
  - sudo docker exec ${container_id} lsof /var/run/slapd/ldapi >> /dev/null && (echo 'LDAP IPC open' && exit 0) || (echo 'LDAP IPC closed' && exit 1)
