---
  - block:
    - name: Enable ldaps
      set_fact:
        slapd_protocols: "{{ slapd_protocols + ' ldaps:///'}}"

    - name: Update protocols
      lineinfile:
        path: "{{ slapd_defaults_path }}"
        regexp: "{{ slapd_protocols_line_regex}}"
        line: '{{ slapd_protocols_line }}="{{ slapd_protocols }}"'
      notify: restart slapd
      become: true
    when: slapd_ssl

  - block:
    - name: Set CA Cert to self signed
      set_fact:
        slapd_ssl_cert_ca_path: "{{ slapd_ssl_cert_path }}"

    - name: Generate Self Signed Certificate
      shell: openssl req -x509 -nodes -newkey rsa:{{ slapd_ssl_cert_key_length }} -keyout {{ slapd_ssl_cert_key_path }} -out {{ slapd_ssl_cert_path }} -days {{ slapd_ssl_cert_duration }} -subj '/C={{ slapd_ssl_cert_country }}/ST={{ slapd_ssl_cert_state }}/L={{ slapd_ssl_cert_location}}/O={{ slapd_ssl_cert_organization }}/CN={{ slapd_ssl_cert_common_name }}'
      become: true

    - name: Set permissions at private key file
      file:
        path: "{{ slapd_ssl_cert_key_path }}"
        owner: "{{ slapd_server_user }}"
        group: "{{ slapd_server_group }}"
        mode: 0600
      become: true

    - name: Create ldif file
      template:
        src: files/ssl_enable.ldif.y2
        dest: "{{ slapd_tmp_dir}}/ssl_enable.ldif"
        owner: root
        group: root
      become: true

    - name: Execute ldif file
      shell: ldapmodify -Y EXTERNAL -H ldapi:/// -f "{{ slapd_tmp_dir}}"/ssl_enable.ldif
      become: true
    when: slapd_ssl_self_signed and slapd_ssl

  - block:
    - name: Create ldif file
      template:
        src: files/ssl_enable.ldif.y2
        dest: "{{ slapd_tmp_dir}}/ssl_enable.ldif"
        owner: root
        group: root
      become: true

    - name: Execute ldif file
      shell: ldapmodify -Y EXTERNAL -H ldapi:/// < "{{ slapd_tmp_dir}}"/ssl_enable.ldif
      become: true
    when: not slapd_ssl_self_signed and slapd_ssl
